using AgentWorldLab.Application.Abstractions;
using AgentWorldLab.Application.Models;
using AgentWorldLab.Domain.Models;

namespace AgentWorldLab.Infrastructure.Services;

public sealed class ChatService : IChatService
{
    private readonly IThreadService _threadService;
    private readonly ISessionService _sessionService;
    private readonly IAgentOrchestrator _orchestrator;
    private readonly IAuditService _auditService;

    public ChatService(
        IThreadService threadService,
        ISessionService sessionService,
        IAgentOrchestrator orchestrator,
        IAuditService auditService)
    {
        _threadService = threadService;
        _sessionService = sessionService;
        _orchestrator = orchestrator;
        _auditService = auditService;
    }

    public ChatResult Send(
        CurrentUser user,
        string message,
        string sessionId,
        string threadId,
        string cloudProvider,
        string agentFrameworkMode,
        string modelBackendMode,
        string correlationId)
    {
        var thread = _threadService.GetOrCreateThread(sessionId, threadId);
        _sessionService.RegisterThread(sessionId, threadId);

        thread.Messages.Add(new ChatMessage("user", message, DateTimeOffset.UtcNow));
        var reply = _orchestrator.GenerateReply(message, cloudProvider, agentFrameworkMode, modelBackendMode);
        thread.Messages.Add(new ChatMessage("assistant", reply, DateTimeOffset.UtcNow));

        _auditService.Append(new AuditEvent(
            "chat.send",
            user.Email,
            threadId,
            "Success",
            correlationId,
            DateTimeOffset.UtcNow,
            $"message-length={message.Length}"));

        var trace = new List<(string EventType, string Message)>
        {
            ("chat.received", "Message accepted."),
            ("orchestrator.reply", "Reply generated by baseline orchestrator.")
        };

        return new ChatResult(sessionId, threadId, reply, trace);
    }
}
