region                 = "us-east-1"
environment            = "staging"
project                = "storage"
s3_bucket_arn          = "REPLACE_ME_S3_BUCKET_ARN"
bucket_access_role_arn = "REPLACE_ME_IAM_ROLE_ARN"
