environment               = "dev"
region                    = "us-east-1"
students_table_name       = "stu-cert-dev-students"
students_table_arn        = "arn:aws:dynamodb:us-east-1:ACCOUNT_ID:table/stu-cert-dev-students"
certifications_table_name = "stu-cert-dev-certifications"
certifications_table_arn  = "arn:aws:dynamodb:us-east-1:ACCOUNT_ID:table/stu-cert-dev-certifications"
# state_machine_arn       = ""  # Fill after deploying serverless/step-functions
deployment_bucket         = "your-deployment-bucket"
deployment_prefix         = "stu-cert/dev/latest"
log_retention_days        = 7
